/* ============================================
   assets.js — Placeholder image resolver
   Icon Commerce College
   --------------------------------------------
   Components must never hardcode image paths. Import `placeholder()`
   or the `IMAGES` map so the labelled dev placeholders (generated by
   scripts/gen-placeholders.mjs, see design-system §7) can be swapped
   for real assets by changing this one file.

   The generator writes SVGs as `<base>.svg`, so logical names like
   `hero-campus` or `hero-campus.jpg` both resolve to
   `/images/placeholders/hero-campus.svg`.
   ============================================ */

const BASE_PATH = '/images/placeholders';

/**
 * Resolve a logical placeholder name to its public URL.
 * Accepts names with or without an extension (`.jpg`/`.png`/`.svg`).
 *
 * @param {string} name e.g. 'hero-campus', 'hero-campus.jpg'
 * @returns {string} e.g. '/images/placeholders/hero-campus.svg'
 */
export function placeholder(name) {
  if (!name) return `${BASE_PATH}/og-default.svg`;
  const base = String(name)
    .trim()
    .replace(/^.*\//, '') // strip any leading path
    .replace(/\.(png|jpe?g|webp|svg)$/i, '');
  return `${BASE_PATH}/${base}.svg`;
}

/**
 * Real brand logo (hosted on Cloudinary). Two variants by background:
 *   normal — for LIGHT backgrounds (header when solid, mobile drawer, admin
 *            login, the splash loader)
 *   white  — for DARK backgrounds (header over the hero, footer)
 * The wide horizontal lockup already includes the college name, so components
 * render the logo on its own — no separate wordmark text beside it.
 */
export const LOGO = {
  normal:
    'https://res.cloudinary.com/dn9gyaiik/image/upload/v1777447286/icon-logo_ssglnp.png',
  white:
    'https://res.cloudinary.com/dn9gyaiik/image/upload/v1777456540/icon-logo-white_cgp9nr.png',
};

/** Intrinsic logo dimensions (both variants) for CLS-safe width/height. */
export const LOGO_SIZE = { width: 441, height: 74 };

/**
 * Canonical map of logical (camelCase) keys → placeholder URLs.
 * Mirrors the §7 manifest so components reference `IMAGES.heroCampus`
 * instead of raw strings.
 */
export const IMAGES = {
  // Brand
  logo: LOGO.normal,
  favicon: placeholder('favicon'),

  // Hero
  heroCampus: placeholder('hero-campus'),
  heroStudents: placeholder('hero-students'),
  heroLibrary: placeholder('hero-library'),

  // About
  aboutBuilding: placeholder('about-college-building'),
  aboutAerial: placeholder('about-campus-aerial'),
  visionMission: placeholder('vision-mission'),

  // Leadership
  principalMandiraSaha: placeholder('principal-dr-mandira-saha'),
  presidentDipaliBora: placeholder('president-dipali-bora'),
  advisorDebasishBora: placeholder('advisor-debasish-bora'),
  rectorSawponDowerah: placeholder('rector-sawpon-dowerah'),
  directorAcademicRajibDas: placeholder('director-academic-rajib-das'),
  directorDipanjuBora: placeholder('director-dipanju-bora'),
  academicAdvisorNilanjan: placeholder('academic-advisor-nilanjan-bhattacharjee'),

  // Courses
  courseBcom: placeholder('course-bcom'),
  courseBba: placeholder('course-bba'),
  courseBca: placeholder('course-bca'),
  courseBa: placeholder('course-ba'),

  // Departments
  deptArts: placeholder('dept-arts'),
  deptCommerce: placeholder('dept-commerce'),
  deptScience: placeholder('dept-science'),

  // Facilities
  facilityLibrary: placeholder('facility-library'),
  facilityComputerLab: placeholder('facility-computer-lab'),
  facilityCanteen: placeholder('facility-canteen'),
  facilityPlayground: placeholder('facility-playground'),
  facilitySmartClassroom: placeholder('facility-smart-classroom'),
  facilityWifi: placeholder('facility-wifi'),

  // Faculty
  facultyPlaceholder: placeholder('faculty-placeholder'),

  // Gallery (1–12)
  gallery: Array.from({ length: 12 }, (_, i) => placeholder(`gallery-${i + 1}`)),

  // Events
  eventCollegeWeek: placeholder('event-college-week'),
  eventCookingCompetition: placeholder('event-cooking-competition'),
  eventIconShield: placeholder('event-icon-shield'),
  eventIconTrophy: placeholder('event-icon-trophy'),

  // Misc
  testimonialAvatar: placeholder('testimonial-avatar'),
  prospectusCover: placeholder('prospectus-cover'),
  mapLocation: placeholder('map-location'),
  ogDefault: placeholder('og-default'),
};

export default IMAGES;
